README.md

Adding clipboard managers section and some clipboard managers.

Adding clipboard managers section.

---

README.md

Found a mistake in the name of the display manager

Fix SSDM to SDDM

---

README.md

Added anyrun to the README.md file in the appropriate section.

Add anyrun to README.md

---

README.md

[hyprland-per-window-layout](https://github.com/MahouShoujoMivutilde/hyprland-per-window-layout).
Let me know if you want it in different place on the list etc.

Added hyprland-per-window-layout

---

README.md

Disclosure: I am the author of wl-screenrec

Add wl-screenrec to recording tool

---

README.md

nwg-{panel, dock-hyprland, drawer, bar} & Hyprshot

More tools to the box

---

README.md

I don't know if this is the right way to add it 🤔

Add `Ianny`

---

README.md

The old name (hyprland-touch-gestures) was too wordy so I renamed it :D

Update plugin name for hyprgrass

---

README.md

Adds https://github.com/donovanglover/hyprdim

feat: add hyprdim

---

README.md

Added [tree-sitter-hypr](https://github.com/luckasRanarison/tree-sitter-hypr) in the README.

Add tree-sitter-hypr

---

README.md

A plugin I wrote that allows you to grab a workspace from possibly another monitor.

grab-workspace

---

README.md

Adds https://github.com/donovanglover/hyprnome

feat: add hyprnome

---

README.md

Can I add hycov plugin into awesome-hyprland?
I want to share it with more people.

add hycov plugin

---

README.md

I've been using wluma with hyprland recently and its super useful to keep the screen at a comfortable brightness level.

Add wluma to "Display" section

---

README.md

change proposition for #39

---

README.md

I made a gui frontend similar to waypaper, with a little bit more of functionality, mimicking wallpaper engine playlist functionality and more in depth configuration of swww options.

Add waypaper engine

---

README.md

Add a new pyprland plugin to the list

add shortcuts_menu

---

README.md

it's referenced in the hyprland wiki wallpaper section, but not here.  https://github.com/danyspin97/wpaperd

add wpaperd

---

README.md

Not sure if placing it under the Display category is the right choice? Can't find anything else that would fit.

Add Hyprfreeze

---

README.md

update clipman link

---

README.md

we should check the hyprwm org more often with the speed Vaxry creates new things lol

add recent hypr-utilities

---

README.md

fixes #54
this time properly, hopefully

Add wlsunset

---

README.md

Add tuigreet

---

README.md

Also added hyprkool because I'm impatient, so #62 is obsolete now

Add Workspace section

---

README.md

I'm gonna deprecate this and ask people to use hypridle instead.

Remove wscreensaver-bridge

---

README.md

Adding [hyprscroller](https://github.com/dawsers/hyprscroller), a layout plugin similar to PaperWM or niri.

Added hyprscroller

---

README.md

pyprland: add two new plugins

---

README.md

decoration {
dim_inactive = true
dim_strength = 0.4
}

hyprdim: notify user that they can do this with stock Hyprland

---

README.md

 add hyprslidr and hyprexpo

---

README.md

Reverts hyprland-community/awesome-hyprland#68
https://github.com/hyprland-community/awesome-hyprland/pull/68#issuecomment-2071298918

Revert "hyprdim: notify user that they can do this with stock Hyprland"

---

README.md

tfw your whole program can be replaced by lines of hyprland config
broken + archived

Remove no_decorations_when_only

---

README.md

feat: add hyprnavi

---

README.md

Rename sysvol to syshud

---

README.md

[Demo](https://www.reddit.com/r/unixporn/comments/1ekgcpa/hyprland_hyprpanel_matugen_perfection/)

Added HyprPanel to the README.

---

README.md

Added sysboard and sysshell
@yavko Hey ho! New stuff has arrived :D

Add more sys stuff

---

README.md

This was announced on Reddit at the start of the year and is stable enough for wider release, though still a WIP.

Add hyprpanel

---

README.md

> a plugin to make your hyprland cursor more realistic, also adds shake to find

add VirtCode/hypr-dynamic-cursors

---

README.md

Hi,
I made a plugin. It's a fork of hypr-darkwindow that adds a background transparency effect by replacing certain colors with transparency based on how close they are to a target color by using the chroma key algorithm. It allows you to add transparent background support to applications that don't normally support it without affecting readability.

Add Hyprchroma plugin

---

README.md

hyprwall repo : https://github.com/nnyyxxxx/hyprwall
hyprgui repo : https://github.com/nnyyxxxx/hyprgui

Added hyprwall and hyprgui.

---

README.md

Still a WIP but stable enough
Repo link: https://github.com/MalpenZibo/ashell

Add ashell statusbar

---

README.md

Saw that hyprsunset wasn't in the list yet so I added it under official tools and display.
Also made the capitalization consistent across the README.

Add Hyprsunset & Capitalization Fixes

---

README.md

A deterministic dynamic output configuration tool that automatically detects and configures connected outputs based on a set of profiles.
https://gitlab.com/w0lff/shikane

Add shikane

---

README.md

HyprGUI project was nuked and is not available now

Remove hyprgui

---

README.md

This is for touchscreen and not touchpad. `touch` as project description is confusing.

Update hyprgrass info

---

README.md

https://github.com/lotos-linux/hypr-dock

add a hypr-dock

---

README.md

Hey!
Thought I would add ly to the list. Have been using it for a while and it's nice if you want a minimalistic display manager.
Greetings :)

Added ly to display managers

---

README.md

Added [hyprmodoro](https://github.com/0xFMD/hyprmodoro) to the Plugins section

Add hyprmodoro

---

README.md

Just an alternative to `cliphist` written in Rust (with a couple extra features)

Add `clipvault`
